name: Build Doxygen GitHub Pages

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Install graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: html
          config_file: Doxyfile
