name: Publish Wheels to Release Page

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Build Wheels
    types:
      - completed
  release:
    types:
      - created


jobs:
  publish_wheels_to_release_page:
    name: Publish wheels to Release Page
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: wheels
          path: wheelhouse

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: wheelhouse/*.whl
