name: Publish Wheels to PyPI

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Build Wheels
    types:
      - completed

jobs:
  publish_wheels_to_pypi:
    name: Publish wheels to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: wheels
          path: wheelhouse

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: wheelhouse
