name: Upload Wheels to GitHub Pages

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  upload_wheels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: wheels

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
          path: 'gh-pages'

      - name: Copy wheels to gh-pages branch
        run: |
          mkdir -p gh-pages/wheels
          cp wheels/*.whl gh-pages/wheels/

      - name: Create index.html for wheels directory
        run: |
          cd gh-pages/wheels
          echo "<!DOCTYPE html>" > index.html
          echo "<html>" >> index.html
          echo "<head><title>Index of wheels</title></head>" >> index.html
          echo "<body>" >> index.html
          echo "<h1>Index of wheels</h1>" >> index.html
          echo "<ul>" >> index.html
          for wheel in *.whl; do
            echo "<li><a href=\"$wheel\">$wheel</a></li>" >> index.html
          done
          echo "</ul>" >> index.html
          echo "</body>" >> index.html
          echo "</html>" >> index.html

      - name: Commit and push wheels to gh-pages branch
        run: |
          cd gh-pages
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add wheels/*.whl wheels/index.html
          git commit -m "Upload wheels to GitHub Pages and update index.html"
          git push
